name       : m17n-db
version    : 1.7.0
release    : 2
source     :
    - http://download.savannah.gnu.org/releases/m17n/m17n-db-1.7.0.tar.gz : a2ba9f80161433d5c06e57915a9cd51f26c6df4a8909723f952cdbb9b48508f0
license    : LGPL-2.1
component  : programming
summary    : Database for the m17n library
description: |
    Database for the m17n library
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
